export const segmentNames = ["a", "b", "c", "d", "e", "f", "g1", "g2", "h", "i", "j", "k", "l", "m"] as const;
export const segmentCodes = {
    "0": ["a", "b", "c", "d", "e", "f", "j", "k"] as const,
    "1": ["b", "c", "j"] as const,
    "2": ["a", "b", "d", "e", "g1", "g2"] as const,
    "3": ["a", "b", "c", "d", "g2"] as const,
    "4": ["b", "c", "f", "g1", "g2"] as const,
    "5": ["a", "c", "d", "f", "g1", "g2"] as const,
    "6": ["a", "c", "d", "e", "f", "g1", "g2"] as const,
    "7": ["a", "j", "l"] as const,
    "8": ["a", "b", "c", "d", "e", "f", "g1", "g2"] as const,
    "9": ["a", "b", "c", "f", "g1", "g2"] as const,
    A: ["a", "b", "c", "e", "f", "g1", "g2"] as const,
    B: ["a", "b", "c", "d", "g2", "i", "l"] as const,
    C: ["a", "d", "e", "f"] as const,
    D: ["a", "b", "c", "d", "i", "l"] as const,
    E: ["a", "d", "e", "f", "g1", "g2"] as const,
    F: ["a", "e", "f", "g1", "g2"] as const,
    G: ["a", "c", "d", "e", "f", "g2"] as const,
    H: ["b", "c", "e", "f", "g1", "g2"] as const,
    I: ["a", "d", "i", "l"] as const,
    J: ["b", "c", "d", "e"] as const,
    K: ["e", "f", "g1", "j", "m"] as const,
    L: ["d", "e", "f"] as const,
    M: ["b", "c", "e", "f", "h", "j"] as const,
    N: ["b", "c", "e", "f", "h", "m"] as const,
    O: ["a", "b", "c", "d", "e", "f"] as const,
    P: ["a", "b", "e", "f", "g1", "g2"] as const,
    Q: ["a", "b", "c", "d", "e", "f", "m"] as const,
    R: ["a", "b", "e", "f", "g1", "g2", "m"] as const,
    S: ["a", "c", "d", "g2", "h"] as const,
    T: ["a", "i", "l"] as const,
    U: ["b", "c", "d", "e", "f"] as const,
    V: ["e", "f", "j", "k"] as const,
    W: ["b", "c", "e", "f", "k", "m"] as const,
    X: ["h", "j", "k", "m"] as const,
    Y: ["h", "j", "l"] as const,
    Z: ["a", "d", "j", "k"] as const,
};
